version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda
      - HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: sh -c "sleep 10 && tail -f /dev/null"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup:
    build:
      context: ./dev
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - LAMBDA_FUNCTION_NAME=lambda_test
    depends_on:
      - localstack
