version: '3.8'

services:
  localstack:
    image: localstack/localstack:1.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda
      - HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=100
    command: sh -c "sleep 10 && tail -f /dev/null"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit inet_dist_listen_min 25672 -rabbit inet_dist_listen_max 25672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs:/var/log/rabbitmq

  setup:
    build:
      context: ./dev
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - LAMBDA_FUNCTION_NAME=lambda_publish_mq
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - localstack
      - rabbitmq